---
strict: true
site_name: {{ cookiecutter.project_name }}
site_description: {{ cookiecutter.project_description }}
site_url: {{ cookiecutter.documentation_url }}
theme:
  name: material
  palette:
    scheme: default
    primary: deep-purple
    accent: deep-purple
  icon:
    logo: material/language-python
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.tabs
repo_name: {{ cookiecutter.github_user }}/{{ cookiecutter.project_name }}
repo_url: {{ cookiecutter.github_repository }}
edit_uri: ""
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  - javascripts/extra.js
nav:
  - Home:
      - Home: index.md
      - Installation: installation.md
      - Changelog: changelog.md
