[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry]
authors = ["{{ cookiecutter.author_name }} <{{ cookiecutter.author_email }}>"]
classifiers = [
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
description = "{{ cookiecutter.project_description }}"
documentation = "{{ cookiecutter.documentation_url }}"
homepage = "{{ cookiecutter.pypi_project }}"
license = "BSD-2-Clause"
name = "{{ cookiecutter.project_name }}"
packages = [
    { include = "{{ cookiecutter.private_module_name }}", from = "src" },
    { include = "{{ cookiecutter.public_module_name }}", from = "src" },
]
readme = "docs/index.md"
repository = "{{ cookiecutter.github_repository }}"
version = "{{ cookiecutter.project_version }}"

[tool.poetry.dependencies]
python = "~3.6 || ~3.7 || ~3.8 || ~3.9"

[tool.poetry.urls]
Changelog = "{{ cookiecutter.changelog_url }}"
Issues = "{{ cookiecutter.issues_url }}"
Twitter = "{{ cookiecutter.twitter_url }}"
