#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

. venv/bin/activate

{% if not cookiecutter.is_private %}export DANGER_GITHUB_API_TOKEN=$(echo $DANGER_GITHUB_API_TOKEN | base64 --decode)

{% endif %}danger ci

cruft check
