#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

. venv/bin/activate

echo "==> Running pytest…"
coverage run -m pytest

echo "==> Running coverage…"
coverage combine
coverage report --fail-under 100
