#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

. venv/bin/activate

coverage run -m pytest

for example in examples/*.py
do
    diff <(coverage run $example) ${example%.py}.log
done

coverage combine

coverage report --fail-under 100
