---
name: pipeline
"on":
  push:
    branches:
      - release
  pull_request:
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0
      - run: |
          git checkout $GITHUB_HEAD_REF
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: ./scripts/install
      - run: ./scripts/check
      - run: ./scripts/test
      - run: ./scripts/review
        if: {% raw %}${{ github.event_name == 'pull_request' }}{% endraw %}
        env:
          DANGER_GITHUB_API_TOKEN: {% if cookiecutter.is_private %}{% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}{% else %}{{ cookiecutter.danger_github_api_token }}{% endif %}
      - run: ./scripts/release
        if: {% raw %}${{ github.ref == 'refs/heads/release' }}{% endraw %}
        env:
          GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}{% if not cookiecutter.is_private %}
          POETRY_PYPI_TOKEN_PYPI: {% raw %}${{ secrets.PYPI_TOKEN }}{% endraw %}{% endif %}
