---
name: pipeline
"on":
  push:
    branches:
      - release
      - develop
  pull_request:
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
          fetch-depth: 0
      - run: |
          git checkout develop || true
          git checkout $GITHUB_HEAD_REF
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - run: ./scripts/install
      - run: ./scripts/check
      - run: ./scripts/test
      - run: ./scripts/review
        if: {% raw %}${{ github.event_name == 'pull_request' }}{% endraw %}
        env:
          DANGER_GITHUB_API_TOKEN: {{ cookiecutter.danger_github_api_token }}
      - run: ./scripts/release
        if: {% raw %}${{ github.ref == 'refs/heads/release' || github.ref == 'refs/heads/develop' }}{% endraw %}
        env:
          GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
          POETRY_PYPI_TOKEN_PYPI: {% raw %}${{ secrets.PYPI_TOKEN }}{% endraw %}
