#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

if [ ! -d venv ]
then
    echo "==> Creating virtual environment…"
    python3.10 -m venv venv
fi

. venv/bin/activate

echo "==> Installing dependencies…"
pip install -r requirements.txt
