#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

echo "==> Generate new project…"
mkdir ../Temp
cruft create --no-input --output-dir=../Temp .
cd ../Temp/*
rm README.md
rm .prettierignore
rm .remarkignore
rm .eslintignore
ln -s docs/index.md README.md
ln -s .gitignore .prettierignore
ln -s .gitignore .remarkignore
ln -s .gitignore .eslintignore

echo "==> Initialize repository…"
git init
git checkout -b release
git commit -m 'Hello world.' --allow-empty
git checkout -b issue-123
git add .
git commit -m 'build: initialize project'

echo "==> Run project tests…"
./scripts/install
./scripts/check
./scripts/test
