#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

echo "==> Generate new project…"
mkdir ../Temp
cruft create -y -c HEAD --output-dir=../Temp .
cd ../Temp/*
rm README.md .prettierignore
ln -s docs/index.md README.md
ln -s .gitignore .prettierignore

echo "==> Initialize repository…"
git init
git commit -m 'Hello world.' --allow-empty
git checkout -b issue-123
git add .
git commit -m 'build: initialize project'

echo "==> Run project tests…"
tox
