#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

. venv/bin/activate

echo "==> Generating new project…"
mkdir ../Temp
cruft create --no-input --extra-context='{"danger_github_api_token":"XYZ"}' --output-dir=../Temp .
cd ../Temp/*
rm README.md
rm .prettierignore
rm .remarkignore
rm .eslintignore
ln -s docs/index.md README.md
ln -s .gitignore .prettierignore
ln -s .gitignore .remarkignore
ln -s .gitignore .eslintignore

echo "==> Initializing repository…"
git init
git checkout -b release
git commit -m 'Hello world.' --allow-empty
git checkout -b issue-123
git add .
git commit -m 'build: initialize project'
cat > tests/test_exceptions.py <<EOF
"""Tests related to exceptions."""
from the_library.exceptions import TheLibraryError
def test_exception() -> None:
    """Check exceptions."""
    assert issubclass(TheLibraryError, Exception)
EOF
git add .

echo "==> Running project tests…"
./scripts/install
./scripts/lint
./scripts/check
./scripts/test
