---
name: site
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: ./scripts/install
      - run: ./scripts/deploy
        env:
          REMOTE: https://${{ github.token }}@github.com/${{ github.repository }}
