---
name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global user.name bot
          git config --global user.email bot@example.com
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - run: ./scripts/install
      - run: ./scripts/test
