---
name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8.12
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9.12
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
      - uses: actions/setup-python@v3
        with:
          python-version: pypy-3.6
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: ./scripts/install
      - run: ./scripts/test
