---
name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        private:
          - 'false'
          - 'true'
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global user.name bot
          git config --global user.email bot@example.com
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: ./scripts/install
      - run: ./scripts/test
        env:
          PRIVATE: ${{ matrix.private }}
