---
name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global user.name bot
          git config --global user.email bot@example.com
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.3
      - uses: actions/setup-node@v4
        with:
          node-version: 22.6.0
      - run: ./scripts/install
      - run: ./scripts/test
